# Generated by Django 4.0.5 on 2022-07-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
    ]
